### ISSUE TITLE
spec should link to paper

### ISSUE THREAD

**Issue by max-mapper** [dat-ecosystem-archive/datprotocol.org#3]
https://www.datprotocol.com/spec.html is the old spec, the more up to date version is https://github.com/datproject/docs/blob/master/papers/dat-paper.md

**Comment by pfrazee** [comment]
I'm in the process of updating spec.html, using the paper as a reference. See my PRs in https://github.com/datproject/docs/pulls. @mafintosh needs to finish reviewing and merging them.

**Comment by max-mapper** [comment]
IMO we should delete hyperdrive_spec.md and just use the dat-paper.md so it's all in one place

**Comment by max-mapper** [comment]
for example https://github.com/pfrazee/docs/blob/5a7cba04c5e20c699b67ab86bf3f7af10a06c244/docs/hyperdrive_spec.md#hyperdrive and https://github.com/datproject/docs/blob/master/papers/dat-paper.md#321-hypercore-and-hyperdrive

**Comment by mafintosh** [comment]
@maxogden sgtm
@pfrazee sorry i'm slow. busy.

**Comment by pfrazee** [comment]
I've put some pretty heavy work into updating hyperdrive_spec. I'd like for us to first get those PRs merged, and then merge as much as possible into the paper, if that's cool.

**Comment by mafintosh** [comment]
@pfrazee i'll get to them soon, promise. need to finish up some js first

**Comment by pfrazee** [comment]
Ok cool

**Comment by max-mapper** [comment]
@pfrazee cool sounds good, def wasnt saying your PRs arent good. just that long term it would be better to just have dat-paper.md, so maybe future effort can go into PRs to that instead

**Comment by pfrazee** [comment]
Yeah totally

**Comment by maryroseMXXXVI** [comment]
totally

**Comment by joehand** [comment]
Specs from DEP repo now. yay
